### PR TITLE
Move IPC logic to polybar-msg

### PR DESCRIPTION
**Pull request by nileshp87**
Quick fix to move the messaging from the /tmp/bottombar fifo into the new polybar-msg.
Makes installation easier, and should fix the multimonitor issues.

### CODE REVIEW

**Comment by nileshp87** [comment]
Should fix #5 and #6

**Comment by dietervanhoof** [comment]
Thanks for contributing. I won't easily be able to test this as I won't have access to my Linux machine.
Can I assume this works on your system?

**Comment by nileshp87** [comment]
I can confirm it works on my system. I didn't have my second monitor to
confirm that. But, nothing should break.

**Comment by dietervanhoof** [comment]
Sweet. Thanks again! Merging this now.

**Pull request merged**
